<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "pmtodo"
 *
 * Auto generated by Extension Builder 2014-07-27
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
    'title' => 'pm Todo- App',
    'description' => 'ToDo App - Eine Full-Responsive Todo-App (gebaut mit Twitters Bootstrap 3). Läuft in TYPO3 CMS ab Version 6.2 bis 7.6.x. Die einzigste Voraussetzung für den Betrieb des Plugins ist Bootstrap. jQuery bringt die Extension schon mit. Kann aber jederzeit mit TypoScript überschrieben werden.',
    'category' => 'plugin',
    'author' => 'pmtodo@pm-newmedia.com',
    'author_email' => 'pmtodo@pm-newmedia.com',
    'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 1,
	'version' => '1.0.1',
  array (
    'depends' =>
    array (
      'typo3' => '6.2.99-7.9.99',
      'bootstrap_package' => '6.2.99-7.99.99',
    ),
    'conflicts' =>
    array (
    ),
    'suggests' =>
    array (
    ),
  ),
);