<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "pmtodo"
 *
 * Auto generated by Extension Builder 2014-07-27
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'pm Todo',
	'description' => '',
	'category' => 'plugin',
	'author' => 'dkoehl@pm-newmedia.com',
	'author_email' => 'dkoehl@pm-newmedia.com',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);